# Generated by Django 6.0.5 on 2026-07-16 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clock", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clockmodel",
            options={"ordering": ["-id"], "verbose_name": "时钟", "verbose_name_plural": "时钟"},
        ),
    ]
