# Generated by Django 6.0.5 on 2026-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerfields",
            name="has_whatsapp",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True=有, False=没有, None=未检测",
                null=True,
                verbose_name="有 WhatsApp",
            ),
        ),
    ]
