# Generated by Django 6.0.5 on 2026-07-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerfields_has_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfields',
            name='phone1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话1'),
        ),
        migrations.AlterField(
            model_name='customerfields',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话2'),
        ),
    ]
