# Generated by Django 6.0.5 on 2026-07-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_null_to_blank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerfields",
            options={"ordering": ["customer_name"], "verbose_name": "客户", "verbose_name_plural": "客户"},
        ),
        migrations.AlterField(
            model_name="customerfields",
            name="customer_code",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, unique=True, verbose_name="客户代码"
            ),
        ),
    ]
