# Generated by Django 6.0.5 on 2026-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_module_module_type_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', '默认'), ('gov', '浓重红色'), ('indigo', '靛蓝'), ('macaron', '马卡龙'), ('teal', '青绿'), ('uniklo', 'uniklo'), ('savawoku', 'Savawoku'), ('kajima', '鹿島ノ森'), ('kajima_warm', '鹿島ノ森（暖色）')], default='default', max_length=20, verbose_name='界面主题'),
        ),
    ]
