# Generated by Django 6.0.3 on 2026-05-09

from django.db import migrations, models


def reset_dopamine_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(theme='dopamine').update(theme='default')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_hitoba_theme'),
    ]

    operations = [
        migrations.RunPython(reset_dopamine_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', '默认'), ('gov', '政府风格'), ('indigo', '靛蓝风格'), ('macaron', '马卡龙风格'), ('teal', '青绿风格'), ('uniklo', '极简风格'), ('savawoku', 'Savawoku 风格')], default='default', max_length=20, verbose_name='界面主题'),
        ),
    ]
