# Generated by Django 6.0.5 on 2026-05-09 15:58

from django.db import migrations, models


def migrate_teal_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(theme='teal').update(theme='default')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_theme'),
    ]

    operations = [
        migrations.RunPython(migrate_teal_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', '默认'), ('gov', '浓重红色'), ('indigo', '靛蓝'), ('macaron', '马卡龙'), ('savawoku', '橙红'), ('kajima', '绿岛森林'), ('odoru', '踊')], default='default', max_length=20, verbose_name='界面主题'),
        ),
    ]
