# Generated by Django 6.0.5 on 2026-07-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_consolidated_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chinaregion",
            name="level",
            field=models.IntegerField(
                choices=[(1, "省级"), (2, "地级市"), (3, "县/区")], db_index=True, verbose_name="层级"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="用户邮箱（可选，用于密码重置、通知等）",
                max_length=254,
                null=True,
                verbose_name="邮箱",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="激活状态"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("manager", "一类用户"), ("leader", "二类用户"), ("employee", "三类用户")],
                db_index=True,
                default="employee",
                help_text="角色：manager=一类用户 / leader=二类用户 / employee=三类用户",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
