# Generated by Django 6.0.5 on 2026-07-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_chinaregion_level_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxonomyitem',
            unique_together={('taxonomy', 'name')},
        ),
    ]
