# Generated by Django 6.0.5 on 2026-07-16 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_module_author_alter_module_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemsetting",
            options={"ordering": ["key"], "verbose_name": "系统设置", "verbose_name_plural": "系统设置"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"], "verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterField(
            model_name="chinaregion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="core.chinaregion",
                verbose_name="父级行政区划",
            ),
        ),
    ]
