# Generated by Django 6.0.4 on 2026-05-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='to_email',
            field=models.TextField(verbose_name='收件人'),
        ),
    ]
