# Generated by Django 6.0.5 on 2026-07-16 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smtp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["name"], "verbose_name": "邮件模板", "verbose_name_plural": "邮件模板"},
        ),
    ]
