# Generated by Django 6.0.5 on 2026-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0002_alter_emaillog_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '已发送'), ('failed', '发送失败')], db_index=True, default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
