# Generated by Django 6.0.5 on 2026-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0003_alter_emaillog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='html_body',
            field=models.TextField(blank=True, default='', verbose_name='HTML正文'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='text_body',
            field=models.TextField(blank=True, default='', verbose_name='纯文本正文'),
        ),
    ]
